[package]
name = "ultimate-tts-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tts = "0.19.2"
inputbot = "0.5.1"